server:
  port: 8083

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  flyway:
    table: flyway_schema_history_divination

services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  tarot-service:
    url: ${TAROT_SERVICE_URL:http://localhost:8082}
