server:
  port: 8084

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  flyway:
    table: flyway_schema_history_notification
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tarot_db}
    user: ${DB_USER:tarot_user}
    password: ${DB_PASSWORD:password}
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:tarot_db}
    username: ${DB_USER:tarot_user}
    password: ${DB_PASSWORD:password}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
