server:
  port: 8081

spring:
  flyway:
    table: flyway_schema_history_user

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:changeThisToAVeryLongSecretKeyForProductionUseAtLeast256BitsLong!!}
  expiration-hours: 24

# Password validation configuration
password:
  min-length: 8
  require-uppercase: true
  require-lowercase: true
  require-digit: true
  require-special: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${random.value}
